server:
  port: 9100
  # http://j9d107.p.ssafy.io:9900/
spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      name: dotori
      profile: default

encrypt:
  key: ${ENCRYPT_KEY}