spring:
  config:
    import: "optional:configserver:http://j9d107.p.ssafy.io:9900/"
  cloud:
    config:
      name: podo
      profile: user
  application:
    name: podo-user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/


#encrypt:
#  key: ${ENCRYPT_KEY}