spring:
  application:
    name: podo-auth-service
  cloud:
    config:
      name: podo
      profile: auth
  config:
    import: "optional:configserver:http://j9d107.p.ssafy.io:9900/"

eureka:
  client:
    service-url:
      defaultZone: http://j9d107.p.ssafy:9761/eureka/

encrypt:
  key: ${ENCRYPT_KEY}